apiVersion: v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
    template:
      metadata:
        labels:
          app: database
      spec:
        containers:
          - name: database
            image: mongo:latest
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: db-credentials
                    key: username
              - name: MONGO_INITDN_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-credentials
                    key: password
        volumeClaimTemplates:
          - metadata:
              name: database-data
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: lGi
